# Generated by Django 4.2.4 on 2023-12-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiroz_bruno_FINAL_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inscrito',
            table='django_seminario',
        ),
    ]
